### ISSUE TITLE
Open source this?

### ISSUE THREAD

**Issue by rclai** [exponentjs/react-native-font-loader#1]
Why isn't this open source? :(

**Comment by ide** [comment]
We don't use this repo. Will close it. Source code for font loading is over here: https://github.com/exponentjs/exponent/blob/master/ios/Exponent/Versioned/Modules/Api/EXFontLoader.m and https://github.com/exponentjs/exponent/blob/435b7bd895a712b7b0791a230cfd0283683e2947/android/app/src/main/java/versioned/host/exp/exponent/modules/api/FontLoaderModule.java

**Comment by rclai** [comment]
Awesome thanks!
